const PDFDocument = require('pdfkit');

/**
 * Generate CSV string from findings
 */
function generateCSV(findings, summary) {
  const headers = ['Resource ID', 'Service', 'Risk Level', 'Issue', 'Recommended Fix'];
  const rows = findings.map((f) => [
    `"${f.id}"`,
    `"${f.service}"`,
    `"${f.riskLevel}"`,
    `"${f.issue.replace(/"/g, '""')}"`,
    `"${f.fix.replace(/"/g, '""')}"`,
  ]);

  let csv = `ShadowGuard Security Report\n`;
  csv += `Generated: ${summary.scannedAt}\n`;
  csv += `Region: ${summary.region}\n`;
  csv += `Total Findings: ${summary.totalResources}\n`;
  csv += `Critical: ${summary.critical} | Medium: ${summary.medium} | Low: ${summary.low}\n\n`;
  csv += headers.join(',') + '\n';
  csv += rows.map((r) => r.join(',')).join('\n');

  return csv;
}

/**
 * Generate PDF buffer from findings
 */
function generatePDF(findings, summary) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Title
    doc.fontSize(24).fillColor('#2563EB').text('ShadowGuard', { align: 'center' });
    doc.fontSize(14).fillColor('#666').text('Cloud Security Risk Analysis Report', { align: 'center' });
    doc.moveDown();

    // Meta
    doc.fontSize(10).fillColor('#333');
    doc.text(`Generated: ${new Date(summary.scannedAt).toLocaleString()}`);
    doc.text(`Region: ${summary.region}`);
    doc.moveDown();

    // Summary box
    doc.fontSize(14).fillColor('#000').text('Executive Summary');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333');
    doc.text(`Total Findings: ${summary.totalResources}`);
    doc.fillColor('#EF4444').text(`Critical: ${summary.critical}`);
    doc.fillColor('#F59E0B').text(`Medium: ${summary.medium}`);
    doc.fillColor('#22C55E').text(`Low: ${summary.low}`);
    doc.moveDown();

    // Service breakdown
    doc.fillColor('#000').fontSize(14).text('Findings by Service');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333');
    for (const [service, count] of Object.entries(summary.services)) {
      if (count > 0) {
        doc.text(`${service}: ${count} finding(s)`);
      }
    }
    doc.moveDown();

    // Detailed findings
    doc.fillColor('#000').fontSize(14).text('Detailed Findings');
    doc.moveDown(0.5);

    findings.forEach((finding, index) => {
      // Check if we need a new page
      if (doc.y > 680) {
        doc.addPage();
      }

      const riskColors = { Critical: '#EF4444', Medium: '#F59E0B', Low: '#22C55E' };

      doc.fontSize(11).fillColor('#000').text(`${index + 1}. [${finding.service}] ${finding.id}`, {
        continued: false,
      });
      doc.fontSize(10).fillColor(riskColors[finding.riskLevel] || '#333').text(`   Risk: ${finding.riskLevel}`);
      doc.fillColor('#333').text(`   Issue: ${finding.issue}`);
      doc.fillColor('#2563EB').text(`   Fix: ${finding.fix}`);
      doc.moveDown(0.5);
    });

    // Footer
    doc.moveDown();
    doc.fontSize(9).fillColor('#999').text('Generated by ShadowGuard — Cloud Security Risk Analysis System', {
      align: 'center',
    });

    doc.end();
  });
}

module.exports = { generateCSV, generatePDF };
